// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/admin/wxtoken.tsx";
import * as $1 from "./routes/admin/wxtry.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/test/wxxml.tsx";
import * as $4 from "./routes/wx.ts";

const manifest = {
  routes: {
    "./routes/admin/wxtoken.tsx": $0,
    "./routes/admin/wxtry.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/test/wxxml.tsx": $3,
    "./routes/wx.ts": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
